defmodule Day07Test do
  use ExUnit.Case

  import Day07

  test "small example" do
    example =
      """
      .......S.......
      ...............
      .......^.......
      ...............
      """

    manifold = example |> build_tachyon_manifold() |> trace_timelines()

    assert manifold |> count_splits() == 1
    assert manifold |> count_timelines() == 2
  end

  test "manifold example input" do
    example =
      """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
      """

    manifold = example |> build_tachyon_manifold() |> trace_timelines()

    assert manifold |> count_splits() == 21
    assert manifold |> count_timelines() == 40
  end
end
